### ISSUE TITLE
The Tests Pertaining to Query.py Fail

### ISSUE THREAD

**Issue by walbrc27** [walbrc27/badges#5]
The [testing_query.py](https://github.com/walbrc27/badges/blob/master/src/badges/tests/test_query.py) tests are inexplicably failing, despite the tests' apparent adherence to Plone's testing framework. Travis' output:
```
Error in test test_create_page (badges.tests.test_query.TestQuery)
Traceback (most recent call last):
  File "/home/travis/build/walbrc27/badges/buildout-cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 333, in run
    self.setUp()
  File "/home/travis/build/walbrc27/badges/src/badges/tests/test_query.py", line 26, in setUp
    title='Test Page',
  File "<decorator-gen-9>", line 2, in create
  File "/home/travis/build/walbrc27/badges/buildout-cache/eggs/plone.api-1.6-py2.7.egg/plone/api/validation.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "<decorator-gen-8>", line 2, in create
  File "/home/travis/build/walbrc27/badges/buildout-cache/eggs/plone.api-1.6-py2.7.egg/plone/api/validation.py", line 131, in wrapped
    return f(*args, **kwargs)
  File "/home/travis/build/walbrc27/badges/buildout-cache/eggs/plone.api-1.6-py2.7.egg/plone/api/content.py", line 100, in create
    '{2}'.format(type, '\n'.join(sorted(types)), e.message)
InvalidParameterError: Cannot add a 'Document' object to the container.
Allowed types are:
Badge
No such content type: Document
```
The problematic code in question (from [testing_query.py](https://github.com/walbrc27/badges/blob/master/src/badges/tests/test_query.py)):
```
self.page = api.content.create(
     container=self.portal,
     type='Document',
     id='test-page',
     title='Test Page',
 )
```
No such content type as a Document? Why? Is the test code [incorrect](https://docs.plone.org/develop/plone.api/docs/content.html#content-create-example)?

**Comment by walbrc27** [comment]
The solution to this was that the [types.xml](https://github.com/walbrc27/badges/blob/master/src/badges/profiles/default/types.xml) file had to have a definition in it for 'Document' before that portal_type could be used. After adding
```
<object meta_type="Dexterity FTI" name="Document" />
```
to the file, the problem was fixed.
